# Generated by Django 4.2.2 on 2023-07-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('User_Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
                ('Confirm_Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Doctor_name', models.CharField(max_length=50)),
                ('Doctor_gender', models.CharField(max_length=10)),
                ('Doctor_email', models.EmailField(max_length=30)),
                ('Doctor_mobile', models.IntegerField()),
                ('Doctor_specialization', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Anesthesiologists', 'Anesthesiologists'), ('Surgeons', 'Surgeons'), ('Critical Care Medicine Specialists', 'Critical Care Medicine Specialists'), ('Endocrinologists', 'Endocrinologists'), ('Gastroenterologists', 'Gastroenterologists'), ('Pediatricians', 'Pediatricians'), ('Neurologists', 'Neurologists'), ('Psychiatrists', 'Psychiatrists'), ('General Surgeons', 'General Surgeons')], default='', max_length=50)),
                ('Doctor_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Patient_name', models.CharField(max_length=40)),
                ('Patient_email', models.EmailField(max_length=30)),
                ('Patient_gender', models.CharField(max_length=10)),
                ('Patient_mobile', models.IntegerField()),
                ('Patient_address', models.CharField(max_length=250)),
                ('Patient_disease', models.CharField(max_length=50)),
                ('Admit_Date', models.DateField()),
                ('Doctor_idAssign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PI_hospital.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Pat_DischargeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=30)),
                ('Doctor_Name', models.CharField(max_length=40)),
                ('Patient_address', models.CharField(max_length=40)),
                ('Patient_mobile', models.CharField(max_length=20, null=True)),
                ('Patient_disease', models.CharField(max_length=100, null=True)),
                ('Admit_Date', models.DateField()),
                ('Discharge_Date', models.DateField()),
                ('Total_days', models.PositiveIntegerField()),
                ('Room_Charge', models.PositiveIntegerField()),
                ('Medicine_Cost', models.PositiveIntegerField()),
                ('Doctor_Fee', models.PositiveIntegerField()),
                ('Other_Charge', models.PositiveIntegerField()),
                ('Total_Bill_Amt', models.PositiveIntegerField()),
                ('Patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PI_hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Patient_name', models.CharField(max_length=40)),
                ('Doctor_name', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=500)),
                ('Appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Appointment_Date', models.DateField(auto_now=True)),
                ('App_Confirmation', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='', max_length=50)),
                ('Doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PI_hospital.doctor')),
                ('Patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PI_hospital.patient')),
            ],
        ),
    ]
